package io.github.connellite.microorm.schema;

import io.github.connellite.microorm.dialect.Dialect;
import io.github.connellite.microorm.mapping.EntityField;
import io.github.connellite.microorm.mapping.EntityModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

public final class OracleSchemaManager extends AbstractSchemaManager {

    public OracleSchemaManager(Dialect dialect) {
        super(dialect);
    }

    @Override
    protected Set<String> existingColumns(Connection connection, EntityModel model) throws SQLException {
        if (!tableExists(connection, model.tableName())) {
            return Set.of();
        }
        Set<String> columns = new HashSet<>();
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT column_name
                FROM all_tab_columns
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND table_name = ?
                """)) {
            ps.setString(1, model.tableName());
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    columns.add(normalize(rs.getString("column_name")));
                }
            }
        }
        return columns;
    }

    private boolean tableExists(Connection connection, String tableName) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_objects
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND object_name = ?
                  AND object_type = 'TABLE'
                """)) {
            ps.setString(1, tableName);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    @Override
    protected boolean indexExists(Connection connection, EntityModel model, EntityField field) throws SQLException {
        String indexName = indexName(model, field);
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_indexes
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND table_name = ?
                  AND index_name = ?
                """)) {
            ps.setString(1, model.tableName());
            ps.setString(2, indexName);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    @Override
    protected String baseType(EntityField f) {
        if (!f.sqlType().isBlank()) {
            return f.sqlType();
        }
        Class<?> t = f.javaType();
        if (t == long.class || t == Long.class) {
            return "NUMBER(19)";
        }
        if (t == int.class || t == Integer.class || t == short.class || t == Short.class || t == byte.class || t == Byte.class) {
            return "NUMBER(10)";
        }
        if (t == boolean.class || t == Boolean.class) {
            return "NUMBER(1)";
        }
        if (t == double.class || t == Double.class) {
            return "BINARY_DOUBLE";
        }
        if (t == float.class || t == Float.class) {
            return "BINARY_FLOAT";
        }
        if (t == String.class) {
            return "VARCHAR2(" + (f.length() > 0 ? f.length() : 255) + ")";
        }
        if (t == UUID.class) {
            return "RAW(16)";
        }
        throw new IllegalArgumentException("Unsupported field type for Oracle DDL: " + t.getName());
    }

    @Override
    protected String autoIncrementPrimaryKeyDefinition(EntityField field) {
        return baseType(field) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }
}
