package io.github.connellite.microorm.schema;

import io.github.connellite.microorm.dialect.Dialect;
import io.github.connellite.microorm.mapping.EntityField;
import io.github.connellite.microorm.mapping.EntityModel;
import io.github.connellite.microorm.sql.SqlIdentifier;
import io.github.connellite.microorm.type.UuidStorage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import java.util.UUID;

public final class OracleSchemaManager extends AbstractSchemaManager {

    public OracleSchemaManager(Dialect dialect) {
        super(dialect);
    }

    @Override
    protected Set<String> existingColumns(Connection connection, EntityModel model) throws SQLException {
        String owner = owner(model);
        String table = model.catalogTableName(dialect);
        if (!tableExists(connection, owner, table)) {
            return Set.of();
        }
        Set<String> columns = caseInsensitiveNullSkippingSet();
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT column_name
                FROM all_tab_columns
                WHERE owner = COALESCE(?, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'))
                  AND table_name = ?
                """)) {
            ps.setString(1, owner);
            ps.setString(2, table);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    columns.add(rs.getString("column_name"));
                }
            }
        }
        return columns;
    }

    private boolean tableExists(Connection connection, String owner, String tableName) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_objects
                WHERE owner = COALESCE(?, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'))
                  AND object_name = ?
                  AND object_type = 'TABLE'
                """)) {
            ps.setString(1, owner);
            ps.setString(2, tableName);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    @Override
    protected boolean indexExists(Connection connection, EntityModel model, EntityField field) throws SQLException {
        String indexName = indexName(model, field);
        String owner = owner(model);
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_indexes
                WHERE owner = COALESCE(?, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'))
                  AND table_name = ?
                  AND index_name = ?
                """)) {
            ps.setString(1, owner);
            ps.setString(2, model.catalogTableName(dialect));
            ps.setString(3, dialect.catalogName(SqlIdentifier.unquoted(indexName)));
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    private String owner(EntityModel model) {
        return model.catalogSchemaName(dialect);
    }

    @Override
    protected String baseTypeForJava(Class<?> t, int length) {
        if (t == long.class || t == Long.class) {
            return "NUMBER(19)";
        }
        if (t == int.class || t == Integer.class || t == short.class || t == Short.class || t == byte.class || t == Byte.class) {
            return "NUMBER(10)";
        }
        if (t == boolean.class || t == Boolean.class) {
            return "NUMBER(1)";
        }
        if (t == double.class || t == Double.class) {
            return "BINARY_DOUBLE";
        }
        if (t == float.class || t == Float.class) {
            return "BINARY_FLOAT";
        }
        if (t == String.class) {
            return "VARCHAR2(" + (length > 0 ? length : 255) + ")";
        }
        if (t == UUID.class) {
            UuidStorage storage = dialect.valueMapper().uuidStorage();
            if (storage == UuidStorage.MICROSOFT_GUID) {
                throw new IllegalArgumentException("MICROSOFT_GUID UUID storage is supported only by MSSQL DDL");
            }
            return storage == UuidStorage.STRING ? "VARCHAR2(36)" : "RAW(16)";
        }
        throw new IllegalArgumentException("Unsupported field type for Oracle DDL: " + t.getName());
    }

    @Override
    protected String autoIncrementPrimaryKeyDefinition(EntityField field) {
        return baseType(field) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    protected String indexName(EntityModel model, EntityField field) {
        String name = super.indexName(model, field);
        if (name.length() <= 30) {
            return name;
        }
        int hash = Math.abs(name.hashCode()) % 10000;
        String suffix = "_" + hash;
        return name.substring(0, 30 - suffix.length()) + suffix;
    }
}
