package io.github.connellite.microorm.schema;

import io.github.connellite.microorm.dialect.Dialect;
import io.github.connellite.microorm.mapping.EntityField;
import io.github.connellite.microorm.mapping.EntityModel;

import java.util.UUID;

public final class PostgresSchemaManager extends AbstractSchemaManager {

    public PostgresSchemaManager(Dialect dialect) {
        super(dialect);
    }

    @Override
    protected String baseTypeForJava(Class<?> t, int length) {
        if (t == long.class || t == Long.class) {
            return "BIGINT";
        }
        if (t == int.class || t == Integer.class || t == short.class || t == Short.class || t == byte.class || t == Byte.class) {
            return "INTEGER";
        }
        if (t == boolean.class || t == Boolean.class) {
            return "BOOLEAN";
        }
        if (t == double.class || t == Double.class) {
            return "DOUBLE PRECISION";
        }
        if (t == float.class || t == Float.class) {
            return "REAL";
        }
        if (t == String.class) {
            return length > 0 ? "VARCHAR(" + length + ")" : "TEXT";
        }
        if (t == UUID.class) {
            return "UUID";
        }
        throw new IllegalArgumentException("Unsupported field type for PostgreSQL DDL: " + t.getName());
    }

    @Override
    protected String autoIncrementPrimaryKeyDefinition(EntityField field) {
        return baseType(field) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    protected String dropTableDdl(EntityModel model) {
        return "DROP TABLE IF EXISTS " + model.sqlTableName(dialect);
    }
}
