package io.github.connellite.microorm.dynamic.schema;

import io.github.connellite.microorm.dialect.Dialect;
import io.github.connellite.microorm.dynamic.Column;
import io.github.connellite.microorm.dynamic.DynamicTable;
import io.github.connellite.microorm.dynamic.LogicalType;
import io.github.connellite.microorm.sql.SqlIdentifier;
import io.github.connellite.microorm.type.UuidStorage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;

/** Oracle Database DDL for runtime tables. */
public final class OracleDynamicSchemaManager extends AbstractDynamicSchemaManager {

    public OracleDynamicSchemaManager(Dialect dialect) {
        super(dialect);
    }

    @Override
    protected Set<String> existingColumns(Connection connection, DynamicTable table) throws SQLException {
        String tableName = dialect.catalogName(table.tableIdentifier());
        if (!tableExists(connection, tableName)) {
            return Set.of();
        }
        Set<String> columns = new HashSet<>();
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT column_name
                FROM all_tab_columns
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND table_name = ?
                """)) {
            ps.setString(1, tableName);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    columns.add(normalize(rs.getString("column_name")));
                }
            }
        }
        return columns;
    }

    @Override
    public boolean tableExists(Connection connection, DynamicTable table) throws SQLException {
        return tableExists(connection, dialect.catalogName(table.tableIdentifier()));
    }

    @Override
    protected String baseTypeForLogical(LogicalType type, int length) {
        return switch (type) {
            case STRING -> "VARCHAR2(" + (length > 0 ? length : 255) + ")";
            case TEXT -> "CLOB";
            case INT -> "NUMBER(10)";
            case LONG -> "NUMBER(19)";
            case BOOL -> "NUMBER(1)";
            case UUID -> uuidType();
            case DECIMAL -> "NUMBER(19,4)";
            case DOUBLE -> "BINARY_DOUBLE";
            case DATETIME -> "TIMESTAMP";
            case DATE -> "DATE";
        };
    }

    private String uuidType() {
        UuidStorage storage = dialect.valueMapper().uuidStorage();
        if (storage == UuidStorage.MICROSOFT_GUID) {
            throw new IllegalArgumentException("MICROSOFT_GUID UUID storage is supported only by MSSQL DDL");
        }
        return storage == UuidStorage.STRING ? "VARCHAR2(36)" : "RAW(16)";
    }

    @Override
    protected String autoIncrementPrimaryKeyDefinition(Column column) {
        return baseType(column) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }

    @Override
    protected String indexName(DynamicTable table, Column column) {
        String name = super.indexName(table, column);
        if (name.length() <= 30) {
            return name;
        }
        int hash = Math.abs(name.hashCode()) % 10000;
        String suffix = "_" + hash;
        return name.substring(0, 30 - suffix.length()) + suffix;
    }

    @Override
    protected boolean indexExists(Connection connection, DynamicTable table, Column column) throws SQLException {
        String indexName = indexName(table, column);
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_indexes
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND table_name = ?
                  AND index_name = ?
                """)) {
            ps.setString(1, dialect.catalogName(table.tableIdentifier()));
            ps.setString(2, dialect.catalogName(SqlIdentifier.unquoted(indexName)));
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }

    private boolean tableExists(Connection connection, String tableName) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                SELECT 1
                FROM all_objects
                WHERE owner = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
                  AND object_name = ?
                  AND object_type = 'TABLE'
                """)) {
            ps.setString(1, tableName);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next();
            }
        }
    }
}
