package io.github.connellite.microorm.dynamic.schema;

import io.github.connellite.microorm.dialect.Dialect;
import io.github.connellite.microorm.dynamic.Column;
import io.github.connellite.microorm.dynamic.DynamicTable;
import io.github.connellite.microorm.dynamic.LogicalType;
import io.github.connellite.microorm.type.UuidStorage;

/** PostgreSQL DDL for runtime tables. */
public final class PostgresDynamicSchemaManager extends AbstractDynamicSchemaManager {

    public PostgresDynamicSchemaManager(Dialect dialect) {
        super(dialect);
    }

    @Override
    protected String dropTableDdl(DynamicTable table) {
        return "DROP TABLE IF EXISTS " + dialect.sqlName(table.tableIdentifier());
    }

    @Override
    protected String baseTypeForLogical(LogicalType type, int length) {
        return switch (type) {
            case STRING -> length > 0 ? "VARCHAR(" + length + ")" : "VARCHAR(255)";
            case TEXT -> "TEXT";
            case INT -> "INTEGER";
            case LONG -> "BIGINT";
            case BOOL -> "BOOLEAN";
            case UUID -> uuidType();
            case DECIMAL -> "NUMERIC(19,4)";
            case DOUBLE -> "DOUBLE PRECISION";
            case DATETIME -> "TIMESTAMP";
            case DATE -> "DATE";
        };
    }

    private String uuidType() {
        UuidStorage storage = dialect.valueMapper().uuidStorage();
        if (storage == UuidStorage.BINARY || storage == UuidStorage.MICROSOFT_GUID) {
            return "BYTEA";
        }
        if (storage == UuidStorage.STRING) {
            return "TEXT";
        }
        return "UUID";
    }

    @Override
    protected String autoIncrementPrimaryKeyDefinition(Column column) {
        return baseType(column) + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    }
}
