package io.github.connellite.microorm;

import org.testcontainers.containers.MSSQLServerContainer;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.containers.OracleContainer;
import org.testcontainers.containers.PostgreSQLContainer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Function;
import java.util.stream.Stream;

public final class DialectTestSupport {

    private static final Duration STARTUP_TIMEOUT = Duration.ofMinutes(10);

    private static final ReentrantLock POSTGRES_LOCK = new ReentrantLock(true);
    private static final ReentrantLock MYSQL_LOCK = new ReentrantLock(true);
    private static final ReentrantLock MSSQL_LOCK = new ReentrantLock(true);
    private static final ReentrantLock ORACLE_LOCK = new ReentrantLock(true);

    private static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine")
            .withStartupTimeout(STARTUP_TIMEOUT);
    private static final MySQLContainer<?> MYSQL = new MySQLContainer<>("mysql:8.4")
            .withUrlParam("connectTimeout", "10000")
            .withUrlParam("socketTimeout", "10000")
            .withStartupTimeout(STARTUP_TIMEOUT);
    private static final MSSQLServerContainer<?> MSSQL = new MSSQLServerContainer<>("mcr.microsoft.com/mssql/server:2022-latest")
            .acceptLicense()
            .withUrlParam("trustServerCertificate", "true")
            .withUrlParam("loginTimeout", "10")
            .withUrlParam("socketTimeout", "10000")
            .withStartupTimeout(STARTUP_TIMEOUT);
    private static final OracleContainer ORACLE = new OracleContainer("gvenzl/oracle-xe:21-slim-faststart")
            .withStartupTimeout(STARTUP_TIMEOUT);

    private DialectTestSupport() {
    }

    public static Stream<DialectFixture> dialects() {
        return Stream.of(sqlite(), postgres(), mysql(), mssql(), oracle());
    }

    public static DialectFixture sqlite() {
        return new DialectFixture(
                "SQLite",
                () -> DriverManager.getConnection("jdbc:sqlite::memory:"),
                MicroOrm::sqlite,
                "CREATE TABLE %s (id INTEGER PRIMARY KEY AUTOINCREMENT)");
    }

    public static DialectFixture postgres() {
        return new DialectFixture(
                "PostgreSQL",
                () -> LockedConnectionSupport.open(POSTGRES_LOCK, POSTGRES, "PostgreSQL", STARTUP_TIMEOUT,
                        () -> DriverManager.getConnection(
                                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword())),
                MicroOrm::postgres,
                "CREATE TABLE %s (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
    }

    public static DialectFixture mysql() {
        return new DialectFixture(
                "MySQL",
                () -> {
                    Connection connection = LockedConnectionSupport.open(MYSQL_LOCK, MYSQL, "MySQL", STARTUP_TIMEOUT,
                            () -> DriverManager.getConnection(
                                    mysqlJdbcUrl(MYSQL), MYSQL.getUsername(), MYSQL.getPassword()));
                    try {
                        try (Statement st = connection.createStatement()) {
                            st.execute("SET SESSION lock_wait_timeout = 15");
                            st.execute("SET SESSION innodb_lock_wait_timeout = 15");
                        }
                        return connection;
                    } catch (SQLException e) {
                        try {
                            connection.close();
                        } catch (SQLException closeError) {
                            e.addSuppressed(closeError);
                        }
                        throw e;
                    }
                },
                MicroOrm::mysql,
                "CREATE TABLE %s (id BIGINT AUTO_INCREMENT PRIMARY KEY)");
    }

    public static DialectFixture mssql() {
        return new DialectFixture(
                "MSSQL",
                () -> LockedConnectionSupport.open(MSSQL_LOCK, MSSQL, "MSSQL", STARTUP_TIMEOUT,
                        () -> DriverManager.getConnection(
                                mssqlJdbcUrl(MSSQL),
                                MSSQL.getUsername(),
                                MSSQL.getPassword())),
                MicroOrm::mssql,
                "CREATE TABLE %s (id BIGINT IDENTITY(1,1) PRIMARY KEY)");
    }

    public static DialectFixture oracle() {
        return new DialectFixture(
                "Oracle",
                () -> LockedConnectionSupport.open(ORACLE_LOCK, ORACLE, "Oracle", STARTUP_TIMEOUT,
                        () -> DriverManager.getConnection(
                                ORACLE.getJdbcUrl(), ORACLE.getUsername(), ORACLE.getPassword())),
                MicroOrm::oracle,
                "CREATE TABLE %s (id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
    }

    static String mysqlJdbcUrl(MySQLContainer<?> mysql) {
        String url = mysql.getJdbcUrl();
        String separator = url.contains("?") ? "&" : "?";
        return url + separator + "sessionVariables=lock_wait_timeout=15,innodb_lock_wait_timeout=15";
    }

    static String mssqlJdbcUrl(MSSQLServerContainer<?> mssql) {
        String url = mssql.getJdbcUrl();
        if (!url.contains("trustServerCertificate=")) {
            url += ";trustServerCertificate=true";
        }
        if (!url.contains("loginTimeout=")) {
            url += ";loginTimeout=10";
        }
        if (!url.contains("socketTimeout=")) {
            url += ";socketTimeout=10000";
        }
        return url;
    }

    public static void dropTables(Connection connection, String... tableNames) throws SQLException {
        for (String tableName : tableNames) {
            dropTable(connection, tableName);
        }
    }

    public static void dropTable(Connection connection, String tableName) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            String database = connection.getMetaData().getDatabaseProductName().toLowerCase();
            if (database.contains("oracle")) {
                statement.execute(oracleDropTable(tableName));
            } else if (database.contains("microsoft")) {
                statement.execute("IF OBJECT_ID('" + tableName + "', 'U') IS NOT NULL DROP TABLE " + tableName);
            } else {
                statement.execute("DROP TABLE IF EXISTS " + tableName);
            }
        }
    }

    public static String oracleDropTable(String tableName) {
        return "BEGIN EXECUTE IMMEDIATE 'DROP TABLE " + tableName + "'; "
                + "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;";
    }

    public static boolean columnExists(Connection connection, String tableName, String columnName) throws SQLException {
        for (String catalog : metadataCatalogs(connection)) {
            for (String schema : metadataSchemas(connection)) {
                for (String table : metadataNames(tableName)) {
                    for (String column : metadataNames(columnName)) {
                        try (ResultSet rs = connection.getMetaData().getColumns(catalog, schema, table, column)) {
                            if (rs.next()) {
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }

    public static boolean indexExists(Connection connection, String tableName, String indexName) throws SQLException {
        for (String catalog : metadataCatalogs(connection)) {
            for (String schema : metadataSchemas(connection)) {
                for (String table : metadataNames(tableName)) {
                    try (ResultSet rs = connection.getMetaData().getIndexInfo(catalog, schema, table, false, false)) {
                        while (rs.next()) {
                            if (indexName.equalsIgnoreCase(rs.getString("INDEX_NAME"))) {
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }

    private static Set<String> metadataCatalogs(Connection connection) throws SQLException {
        Set<String> values = new LinkedHashSet<>();
        values.add(null);
        values.add(connection.getCatalog());
        return values;
    }

    private static Set<String> metadataSchemas(Connection connection) throws SQLException {
        Set<String> values = new LinkedHashSet<>();
        values.add(null);
        values.add(connection.getSchema());
        return values;
    }

    private static Set<String> metadataNames(String name) {
        Set<String> values = new LinkedHashSet<>();
        values.add(name);
        values.add(name.toUpperCase());
        values.add(name.toLowerCase());
        return values;
    }

    public record DialectFixture(
            String name,
            ConnectionFactory connectionFactory,
            Function<Connection, MicroOrm> ormFactory,
            String autoIncrementIdTableDdl) {

        public Connection openConnection() throws SQLException {
            return connectionFactory.open();
        }

        public MicroOrm createOrm(Connection connection) {
            return ormFactory.apply(connection);
        }

        public String autoIncrementIdTableDdl(String tableName) {
            return autoIncrementIdTableDdl.formatted(tableName);
        }

        @Override
        public String toString() {
            return name;
        }
    }

    @FunctionalInterface
    public interface ConnectionFactory {
        Connection open() throws SQLException;
    }
}
